openapi: 3.0.1
info:
  title: AnyEx 接口文档
  description: "文档正在拼命完善中……"
  contact:
    name: AnyEx Project
    email: me@bluerain.io
    url: https://anyex.bluerain.io
  license:
    name: MIT 许可证
    url: "https://opensource.org/licenses/mit-license.php"
  version: alpha
servers:
  - url: "/"
tags:
  - name: 认证
    description: 有关认证的操作和获取接口
  - name: 类别
    description: 有关类别的操作和获取接口
  - name: 标签
    description: 有关标签的操作和获取接口
  - name: 文章
    description: 有关文章的操作和获取接口
paths:
  /token/gen:
    post:
      tags:
        - 认证
      summary: 生成认证令牌
      operationId: genToken
      requestBody:
        description: 管理员信息
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Admin"
      responses:
        200:
          description: 令牌响应
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"

        400:
          description: 错误响应
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
  /category/admin:
    post:
      tags:
        - 类别
      summary: 添加一个类别
      operationId: addCategory
      security: [jwt_auth: []]
      requestBody:
        description: 类别
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        200:
          description: 添加后的类别
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        400:
          description: 错误响应
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"

        401:
          description: 无效授权
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
  /tag/admin:
    post:
      tags:
        - 标签
      summary: 添加一个标签
      operationId: addTag
      security: [jwt_auth: []]
      requestBody:
        description: 标签
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Tag"
      responses:
        200:
          description: 添加后的标签
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tag"
        400:
          description: 错误响应
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"

        401:
          description: 无效授权
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
  /article/admin:
    post:
      tags:
        - 文章
      summary: 添加一个文章
      operationId: addArticle
      security: [jwt_auth: []]
      requestBody:
        description: 文章
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Article"
      responses:
        200:
          description: 添加后的文章
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        400:
          description: 错误响应
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"

        401:
          description: 无效授权
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
    put:
      tags:
        - 文章
      summary: 更新一个文章
      operationId: updateArticle
      security: [jwt_auth: []]
      requestBody:
        description: 文章
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Article"
      responses:
        200:
          description: 更新后的文章
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        400:
          description: 错误响应
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"

        401:
          description: 无效授权
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
  /article/admin/hidden/{id}:
    put:
      tags:
        - 文章
      summary: 隐藏一个文章
      operationId: hiddenArticle
      security: [jwt_auth: []]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 文章的 ID
      responses:
        200:
          description: 隐藏后的文章
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        400:
          description: 错误响应
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"

        401:
          description: 无效授权
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
  /article/admin/{id}:
    delete:
      tags:
        - 文章
      summary: 删除一个文章
      operationId: deleteArticle
      security: [jwt_auth: []]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 文章的 ID
      responses:
        200:
          description: 删除后的文章
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        400:
          description: 错误响应
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"

        401:
          description: 无效授权
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
    get:
      tags:
        - 文章
      summary: 获取后台文章内容
      operationId: getAdminArticle
      security: [jwt_auth: []]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 文章 ID
      responses:
        200:
          description: 文章
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Article"
        400:
          description: 错误响应
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
        401:
          description: 无效授权
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
  /article/admin/normal/{id}:
    put:
      tags:
        - 文章
      summary: 恢复一个文章
      operationId: normalArticle
      security: [jwt_auth: []]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 文章的 ID
      responses:
        200:
          description: 恢复后的文章
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        400:
          description: 错误响应
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
  /article/admin/top/{id}:
    post:
      tags:
        - 文章
      summary: 置顶一个文章
      operationId: topArticle
      security: [jwt_auth: []]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 文章的 ID
      responses:
        200:
          description: 置顶后的文章
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        400:
          description: 错误响应
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
    delete:
      tags:
        - 文章
      summary: 取消文章置顶
      operationId: cancelTopArticle
      security: [jwt_auth: []]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 文章的 ID
      responses:
        200:
          description: 取消置顶后的文章
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        400:
          description: 错误响应
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
  /article/list:
    get:
      tags:
        - 文章
      summary: 获取前台文章列表
      operationId: findArticleList
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: 数据集偏移
        - in: query
          name: limit
          schema:
            type: integer
          description: 数据集大小
        - in: query
          name: category_qname
          schema:
            type: string
          description: 类别(查询)名称
        - in: query
          name: tag_qname
          schema:
            type: string
          description: 标签(查询)名称
      responses:
        200:
          description: 文章列表响应
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"
        400:
          description: 错误响应
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
  /article/admin/list:
    get:
      tags:
        - 文章
      summary: 获取后台文章列表
      operationId: findAdminArticleList
      security: [jwt_auth: []]
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: 数据集偏移
        - in: query
          name: limit
          schema:
            type: integer
          description: 数据集大小
        - in: query
          name: category_qname
          schema:
            type: string
          description: 类别(查询)名称
        - in: query
          name: tag_qname
          schema:
            type: string
          description: 标签(查询)名称
      responses:
        200:
          description: 文章列表响应
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"
        400:
          description: 错误响应
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
        401:
          description: 无效授权
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
  /article/query/{qtext}:
    get:
      tags:
        - 文章
      summary: 获取前台文章内容
      operationId: getArticle
      parameters:
        - in: path
          name: qtext
          required: true
          schema:
            type: string
          description: 文章查询文本
      responses:
        200:
          description: 文章
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Article"
        400:
          description: 错误响应
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrReason"
components:
  schemas:
    Token:
      title: 令牌
      type: object
      properties:
        token:
          type: string
    Admin:
      title: 认证
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    ErrReason:
      title: 错误
      type: object
      properties:
        message:
          type: string
        data:
          type: object
    Category:
      title: 类别
      type: object
      properties:
        id:
          type: integer
        qname:
          type: string
        name:
          type: string
        description:
          type: string
        top:
          type: integer
        inserted_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        res_status:
          type: integer
    Tag:
      title: 标签
      type: object
      properties:
        id:
          type: integer
        qname:
          type: string
        name:
          type: string
        description:
          type: string
        top:
          type: integer
        inserted_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        res_status:
          type: integer
    Article:
      title: 文章
      type: object
      properties:
        id:
          type: integer
        category_id:
          type: integer
        qtext:
          type: string
        title:
          type: string
        preface:
          type: string
        content:
          type: string
        top:
          type: integer
        inserted_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        res_status:
          type: integer
  securitySchemes:
    jwt_auth:
      type: apiKey
      in: header
      name: authorization
