version: '3.1'

services:

  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: sampledb123
      POSTGRES_DB: anyex-dev

  adminer:
    image: adminer
    ports:
      - 5555:8080
