version: '3.1'

services:

  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: sampledb123
      POSTGRES_DB: anyex_prod
    restart: always

  server:
    image: bluerain/anyex
    ports:
      - 8080:8080
    environment:
      ANYEX_DB_NAME: anyex_prod
      ANYEX_DB_USERNAME: postgres
      ANYEX_DB_PASSWORD: sampledb123
      ANYEX_DB_HOSTNAME: db
      ANYEX_SERVER_PORT: 8080
      ANYEX_SERVER_USERNAME: admin
      ANYEX_SERVER_PASSWORD: admin123
      ANYEX_SERVER_SECRET: 7EvrcO4jDM
      ANYEX_SERVER_ARTICLE_MARKDOWN_SUPPORT: "true"
      ANYEX_SERVER_TWEET_MARKDOWN_SUPPORT: "true"
      ANYEX_SERVER_DEFAULT_LIMIT: 50
    depends_on:
      - db
    restart: always
