version: '3.1'

services:

  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: sampledb123
      POSTGRES_DB: anyex-prod
    restart: always

  server:
    image: bluerain/anyex
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always
